/**
 * @file wifi_manager.c
 * @brief AP+STA lifecycle for the IIoT gateway (Phase 0).
 *
 * Boot order: netif init -> default event loop -> Wi-Fi driver init ->
 * mode set to AP+STA -> AP/STA config apply -> start -> register handlers.
 *
 * The implementation is GREEN for the deterministic helper surface
 * (validate_ap_channel, ssid_in_range, password_in_range, format_mac,
 * apply_credentials) and brings up the Wi-Fi driver so the gateway can
 * serve the SPA/REST/WebSocket layer in Fase 1.
 *
 * Credentials come from `wifi_credentials.local.h`, generated by
 * `tools/gen-wifi-credentials.sh` from `/.env` (both gitignored). When
 * the local header is missing or empty, STA association is skipped
 * and the AP starts with Kconfig defaults (typically open on channel 1).
 *
 * The init/deinit pair is **not** idempotent. `wifi_manager_init` must
 * be called exactly once and `wifi_manager_deinit` once at teardown.
 * A second init returns ESP_ERR_INVALID_STATE.
 */

#include "wifi_manager.h"

#include <stdint.h>
#include <stdio.h>
#include <string.h>

#include "esp_event.h"
#include "esp_log.h"
#include "esp_netif.h"
#include "esp_timer.h"
#include "esp_wifi.h"
#include "freertos/FreeRTOS.h"
#include "nvs_flash.h"

#if __has_include("wifi_credentials.local.h")
#include "wifi_credentials.local.h"
#endif

static const char *TAG = "wifi_manager";

/* Module-level state: tracks whether `wifi_manager_init` has been
 * called and stores the resolved credentials for the lifetime of the
 * component. */
static bool s_wifi_started = false;
static wifi_manager_credentials_t s_credentials = {0};

/* Reconnect timer used by the STA disconnect handler. */
static esp_timer_handle_t s_sta_reconnect_timer = NULL;

/* Forward declarations for the static event handler. */
static void wifi_event_handler(void *arg, esp_event_base_t event_base,
                               int32_t event_id, void *event_data);

static void sta_reconnect_after_delay(void *arg)
{
    (void)arg;
    esp_err_t err = esp_wifi_connect();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "STA reconnect failed: %s", esp_err_to_name(err));
    }
}

esp_err_t wifi_manager_validate_ap_channel(uint8_t channel, bool *is_valid)
{
    if (is_valid == NULL) {
        return ESP_ERR_INVALID_ARG;
    }
    *is_valid = (channel >= WIFI_MANAGER_AP_CHANNEL_MIN) &&
                (channel <= WIFI_MANAGER_AP_CHANNEL_MAX);
    return ESP_OK;
}

esp_err_t wifi_manager_ssid_in_range(const char *ssid)
{
    if (ssid == NULL) {
        return ESP_ERR_INVALID_ARG;
    }
    size_t len = strnlen(ssid, WIFI_MANAGER_SSID_MAX_LEN + 1u);
    if (len == 0u) {
        return ESP_ERR_INVALID_ARG;
    }
    if (len > WIFI_MANAGER_SSID_MAX_LEN) {
        return ESP_ERR_INVALID_SIZE;
    }
    return ESP_OK;
}

esp_err_t wifi_manager_password_in_range(const char *password)
{
    if (password == NULL) {
        return ESP_ERR_INVALID_ARG;
    }
    size_t len = strnlen(password, WIFI_MANAGER_PASSWORD_MAX_LEN + 1u);
    if (len > (WIFI_MANAGER_PASSWORD_MAX_LEN - 1u)) {
        return ESP_ERR_INVALID_SIZE;
    }
    return ESP_OK;
}

esp_err_t wifi_manager_format_mac(const uint8_t mac[6], char *out, size_t out_len)
{
    if (mac == NULL || out == NULL || out_len < WIFI_MANAGER_MAC_STR_LEN) {
        return ESP_ERR_INVALID_ARG;
    }
    int written = snprintf(out, out_len, "%02x:%02x:%02x:%02x:%02x:%02x",
                           mac[0], mac[1], mac[2], mac[3], mac[4], mac[5]);
    if (written < 0 || (size_t)written >= out_len) {
        return ESP_ERR_INVALID_SIZE;
    }
    return ESP_OK;
}

esp_err_t wifi_manager_apply_credentials(const wifi_manager_credentials_t *in,
                                         wifi_manager_credentials_t *out)
{
    if (in == NULL || out == NULL) {
        return ESP_ERR_INVALID_ARG;
    }
    memset(out, 0, sizeof(*out));

    out->sta_ssid = in->sta_ssid;
    out->sta_password = in->sta_password;

    if (in->ap_ssid == NULL || in->ap_ssid[0] == '\0') {
        out->ap_ssid = WIFI_MANAGER_AP_DEFAULT_SSID;
    } else {
        out->ap_ssid = in->ap_ssid;
    }

    out->ap_password = in->ap_password;

    if (in->ap_channel == 0u) {
        out->ap_channel = WIFI_MANAGER_AP_DEFAULT_CHANNEL;
    } else {
        out->ap_channel = in->ap_channel;
    }

    if (in->ap_max_connection == 0u) {
        out->ap_max_connection = WIFI_MANAGER_AP_DEFAULT_MAX_CONN;
    } else {
        out->ap_max_connection = in->ap_max_connection;
    }

    return ESP_OK;
}

esp_err_t wifi_manager_init(const wifi_manager_credentials_t *credentials)
{
    if (s_wifi_started) {
        ESP_LOGE(TAG, "wifi_manager_init called twice");
        return ESP_ERR_INVALID_STATE;
    }

    /* Build the effective credentials. The local header may override
     * `ap_password` via WIFI_MGR_LOCAL_AP_PASSWORD, and STA SSID/password
     * via WIFI_MGR_LOCAL_STA_SSID / WIFI_MGR_LOCAL_STA_PASSWORD. */
    wifi_manager_credentials_t effective = {0};

#ifdef WIFI_MGR_LOCAL_STA_SSID
    effective.sta_ssid = WIFI_MGR_LOCAL_STA_SSID;
#else
    effective.sta_ssid = (credentials != NULL) ? credentials->sta_ssid : NULL;
#endif

#ifdef WIFI_MGR_LOCAL_STA_PASSWORD
    effective.sta_password = WIFI_MGR_LOCAL_STA_PASSWORD;
#else
    effective.sta_password = (credentials != NULL) ? credentials->sta_password : NULL;
#endif

    if (credentials != NULL && credentials->ap_ssid != NULL) {
        effective.ap_ssid = credentials->ap_ssid;
    } else {
        effective.ap_ssid = WIFI_MANAGER_AP_DEFAULT_SSID;
    }

#ifdef WIFI_MGR_LOCAL_AP_PASSWORD
    effective.ap_password = WIFI_MGR_LOCAL_AP_PASSWORD;
#else
    effective.ap_password = (credentials != NULL) ? credentials->ap_password : NULL;
#endif

    effective.ap_channel = (credentials != NULL) ? credentials->ap_channel
                                                 : WIFI_MANAGER_AP_DEFAULT_CHANNEL;
    effective.ap_max_connection = (credentials != NULL) ? credentials->ap_max_connection
                                                       : WIFI_MANAGER_AP_DEFAULT_MAX_CONN;

    /* Validate the AP channel up-front. */
    {
        bool channel_ok = false;
        esp_err_t err = wifi_manager_validate_ap_channel(effective.ap_channel, &channel_ok);
        if (err != ESP_OK || !channel_ok) {
            ESP_LOGE(TAG, "Invalid AP channel: %u", effective.ap_channel);
            return ESP_ERR_INVALID_ARG;
        }
    }

    s_credentials = effective;

    ESP_ERROR_CHECK(esp_netif_init());
    ESP_ERROR_CHECK(esp_event_loop_create_default());

    esp_netif_create_default_wifi_ap();
    esp_netif_create_default_wifi_sta();

    wifi_init_config_t cfg = WIFI_INIT_CONFIG_DEFAULT();
    ESP_ERROR_CHECK(esp_wifi_init(&cfg));

    ESP_ERROR_CHECK(esp_wifi_set_mode(WIFI_MODE_APSTA));

    /* AP configuration. */
    wifi_config_t ap_config = {0};
    strncpy((char *)ap_config.ap.ssid, effective.ap_ssid,
            sizeof(ap_config.ap.ssid) - 1u);
    if (effective.ap_password != NULL && effective.ap_password[0] != '\0') {
        strncpy((char *)ap_config.ap.password, effective.ap_password,
                sizeof(ap_config.ap.password) - 1u);
        ap_config.ap.authmode = WIFI_AUTH_WPA2_PSK;
    } else {
        ap_config.ap.authmode = WIFI_AUTH_OPEN;
    }
    ap_config.ap.channel = effective.ap_channel;
    ap_config.ap.max_connection = effective.ap_max_connection;
    ap_config.ap.ssid_hidden = 0;
    ap_config.ap.beacon_interval = 100;

    ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_AP, &ap_config));

    /* STA configuration (only if SSID is present). */
    if (effective.sta_ssid != NULL && effective.sta_ssid[0] != '\0') {
        wifi_config_t sta_config = {0};
        strncpy((char *)sta_config.sta.ssid, effective.sta_ssid,
                sizeof(sta_config.sta.ssid) - 1u);
        if (effective.sta_password != NULL) {
            strncpy((char *)sta_config.sta.password, effective.sta_password,
                    sizeof(sta_config.sta.password) - 1u);
        }
        sta_config.sta.threshold.authmode = WIFI_AUTH_OPEN;
        sta_config.sta.pmf_cfg.capable = true;
        sta_config.sta.pmf_cfg.required = false;

        ESP_ERROR_CHECK(esp_wifi_set_config(WIFI_IF_STA, &sta_config));
        ESP_LOGI(TAG, "STA configured for SSID '%s'", effective.sta_ssid);
    } else {
        ESP_LOGI(TAG, "STA disabled (no SSID in credentials)");
    }

    ESP_ERROR_CHECK(esp_wifi_start());

    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT,
                                               WIFI_EVENT_AP_STACONNECTED,
                                               &wifi_event_handler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT,
                                               WIFI_EVENT_AP_STADISCONNECTED,
                                               &wifi_event_handler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT,
                                               WIFI_EVENT_STA_START,
                                               &wifi_event_handler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT,
                                               WIFI_EVENT_STA_CONNECTED,
                                               &wifi_event_handler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(WIFI_EVENT,
                                               WIFI_EVENT_STA_DISCONNECTED,
                                               &wifi_event_handler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT,
                                               IP_EVENT_STA_GOT_IP,
                                               &wifi_event_handler, NULL));
    ESP_ERROR_CHECK(esp_event_handler_register(IP_EVENT,
                                               IP_EVENT_STA_LOST_IP,
                                               &wifi_event_handler, NULL));

    /* Schedule a one-shot reconnect timer so the disconnect handler
     * can defer the connect call. */
    const esp_timer_create_args_t timer_args = {
        .callback = &sta_reconnect_after_delay,
        .name = "wifi_sta_reconnect",
    };
    ESP_ERROR_CHECK(esp_timer_create(&timer_args, &s_sta_reconnect_timer));

    if (effective.sta_ssid != NULL && effective.sta_ssid[0] != '\0') {
        ESP_ERROR_CHECK(esp_wifi_connect());
    }

    s_wifi_started = true;

    ESP_LOGI(TAG, "wifi_manager_init OK: AP='%s' channel=%u max_conn=%u STA=%s",
             effective.ap_ssid,
             effective.ap_channel,
             effective.ap_max_connection,
             (effective.sta_ssid != NULL && effective.sta_ssid[0] != '\0')
                 ? effective.sta_ssid
                 : "(disabled)");

    return ESP_OK;
}

esp_err_t wifi_manager_deinit(void)
{
    if (!s_wifi_started) {
        return ESP_ERR_INVALID_STATE;
    }

    esp_err_t err = esp_wifi_stop();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "esp_wifi_stop failed: %s", esp_err_to_name(err));
        return err;
    }

    if (s_sta_reconnect_timer != NULL) {
        esp_timer_delete(s_sta_reconnect_timer);
        s_sta_reconnect_timer = NULL;
    }

    err = esp_wifi_deinit();
    if (err != ESP_OK) {
        ESP_LOGE(TAG, "esp_wifi_deinit failed: %s", esp_err_to_name(err));
        return err;
    }

    s_wifi_started = false;
    ESP_LOGI(TAG, "wifi_manager_deinit OK");
    return ESP_OK;
}

static void wifi_event_handler(void *arg, esp_event_base_t event_base,
                               int32_t event_id, void *event_data)
{
    (void)arg;

    if (event_base == WIFI_EVENT) {
        switch (event_id) {
        case WIFI_EVENT_AP_STACONNECTED: {
            wifi_event_ap_staconnected_t *event =
                (wifi_event_ap_staconnected_t *)event_data;
            char mac[WIFI_MANAGER_MAC_STR_LEN] = {0};
            if (wifi_manager_format_mac(event->mac, mac, sizeof(mac)) == ESP_OK) {
                ESP_LOGI(TAG, "AP client connected: MAC=%s aid=%d",
                         mac, event->aid);
            } else {
                ESP_LOGI(TAG, "AP client connected: aid=%d", event->aid);
            }
            break;
        }
        case WIFI_EVENT_AP_STADISCONNECTED: {
            wifi_event_ap_stadisconnected_t *event =
                (wifi_event_ap_stadisconnected_t *)event_data;
            char mac[WIFI_MANAGER_MAC_STR_LEN] = {0};
            if (wifi_manager_format_mac(event->mac, mac, sizeof(mac)) == ESP_OK) {
                ESP_LOGI(TAG, "AP client disconnected: MAC=%s aid=%d reason=%d",
                         mac, event->aid, event->reason);
            } else {
                ESP_LOGI(TAG, "AP client disconnected: aid=%d reason=%d",
                         event->aid, event->reason);
            }
            break;
        }
        case WIFI_EVENT_STA_START: {
            uint8_t primary_channel = 0;
            wifi_second_chan_t second = WIFI_SECOND_CHAN_NONE;
            esp_wifi_get_channel(&primary_channel, &second);
            ESP_LOGI(TAG, "STA start: AP/STA primary channel=%u", primary_channel);
            break;
        }
        case WIFI_EVENT_STA_CONNECTED: {
            wifi_event_sta_connected_t *event =
                (wifi_event_sta_connected_t *)event_data;
            ESP_LOGI(TAG, "STA connected: SSID='%s' channel=%u authmode=%d",
                     event->ssid, event->channel, event->authmode);
            break;
        }
        case WIFI_EVENT_STA_DISCONNECTED: {
            wifi_event_sta_disconnected_t *event =
                (wifi_event_sta_disconnected_t *)event_data;
            ESP_LOGW(TAG, "STA disconnected: reason=%d rssi=%d ssid='%s'",
                     event->reason, event->rssi, event->ssid);
            if (s_sta_reconnect_timer != NULL) {
                esp_timer_stop(s_sta_reconnect_timer);
                esp_timer_start_once(s_sta_reconnect_timer, 1000 * 1000);
            }
            break;
        }
        default:
            break;
        }
    } else if (event_base == IP_EVENT) {
        switch (event_id) {
        case IP_EVENT_STA_GOT_IP: {
            ip_event_got_ip_t *event = (ip_event_got_ip_t *)event_data;
            ESP_LOGI(TAG, "STA got IP: " IPSTR, IP2STR(&event->ip_info.ip));
            break;
        }
        case IP_EVENT_STA_LOST_IP: {
            ESP_LOGW(TAG, "STA lost IP");
            break;
        }
        default:
            break;
        }
    }
}
