#!/usr/bin/env bash
#
# tools/gen-wifi-credentials.sh
#
# Reads the gitignored `/.env` at the repo root and emits
# `firmware/gateway/main/wifi_credentials.local.h` (also gitignored)
# with the Wi-Fi credential macros the gateway expects.
#
# Behavior:
# - If `.env` is missing OR all keys are empty: emit a sentinel file
#   that defines no STA macros and documents the fallback to
#   Kconfig defaults. Build still succeeds with STA disabled and
#   AP open (CI-friendly).
# - If `.env` carries WIFI_MGR_LOCAL_STA_SSID + WIFI_MGR_LOCAL_STA_PASSWORD:
#   emit the macros so wifi_manager.c can pull them in.
# - The AP password (WIFI_MGR_LOCAL_AP_PASSWORD) is optional; when set,
#   it enables WPA2-PSK on the IIoT-Gateway soft-AP.
#
# Usage:
#     bash tools/gen-wifi-credentials.sh            # write the file
#     bash tools/gen-wifi-credentials.sh --dry-run  # print what would be written
#
# Never echo the actual password. The --dry-run mode prints
# `(set)` or `(empty)` for each key, never the literal value.
#
# This script must be invoked from the repo root (the directory that
# contains .env and firmware/). The caller can override the repo root
# with WIFI_MGR_REPO_ROOT=/path/to/repo.

set -euo pipefail

REPO_ROOT="${WIFI_MGR_REPO_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"
ENV_FILE="${REPO_ROOT}/.env"
OUT_FILE="${REPO_ROOT}/firmware/gateway/components/wifi_manager/include/wifi_credentials.local.h"
OUT_DIR="$(dirname "${OUT_FILE}")"

DRY_RUN=0
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=1
fi

# Read a single key from .env. Returns empty string if missing.
read_env() {
    local key="$1"
    if [[ ! -f "${ENV_FILE}" ]]; then
        echo ""
        return
    fi
    # Match `KEY=value` (allow optional surrounding whitespace; ignore
    # comment lines that happen to contain `KEY=`).
    local val
    val="$(grep -E "^[[:space:]]*${key}[[:space:]]*=" "${ENV_FILE}" \
            | tail -n1 \
            | sed -E "s/^[[:space:]]*${key}[[:space:]]*=[[:space:]]*//")"
    # Strip optional double quotes around the value.
    val="${val%\"}"
    val="${val#\"}"
    # Strip optional single quotes.
    val="${val%\'}"
    val="${val#\'}"
    echo "${val}"
}

STA_SSID="$(read_env WIFI_MGR_LOCAL_STA_SSID)"
STA_PASS="$(read_env WIFI_MGR_LOCAL_STA_PASSWORD)"
AP_PASS="$(read_env WIFI_MGR_LOCAL_AP_PASSWORD)"

emit_file() {
    cat <<HEADER
/**
 * @file wifi_credentials.local.h
 * @brief Local Wi-Fi credentials for the gateway (gitignored).
 *
 * Generated by tools/gen-wifi-credentials.sh. Do not edit by hand;
 * the script overwrites this file on every invocation. The source
 * of truth is \`/.env\` at the repo root, also gitignored.
 *
 * Never commit this file. Never paste its contents into an issue,
 * a chat message, or a public log. Keep secrets on disk only.
 */
#pragma once

HEADER

    if [[ -z "${STA_SSID}" && -z "${STA_PASS}" && -z "${AP_PASS}" ]]; then
        cat <<EMPTY
/* No credentials present in .env. STA association disabled.
 * AP runs open with Kconfig defaults (see
 * firmware/gateway/components/wifi_manager/Kconfig.projbuild).
 * To enable STA, set WIFI_MGR_LOCAL_STA_SSID and
 * WIFI_MGR_LOCAL_STA_PASSWORD in .env and re-run
 * tools/gen-wifi-credentials.sh. */

#define WIFI_MGR_CREDENTIALS_SOURCE_NONE 1
EMPTY
        return
    fi

    cat <<PREAMBLE
/* Credentials generated from \`/.env\`. */
/* AP password: $( [[ -n "${AP_PASS}" ]] && echo set || echo empty ) */
/* STA SSID:    $( [[ -n "${STA_SSID}" ]] && echo set || echo empty ) */
/* STA pass:    $( [[ -n "${STA_PASS}" ]] && echo set || echo empty ) */

#define WIFI_MGR_CREDENTIALS_SOURCE_ENV 1

PREAMBLE

    if [[ -n "${STA_SSID}" ]]; then
        printf '#define WIFI_MGR_LOCAL_STA_SSID         "%s"\n' "${STA_SSID}"
    fi
    if [[ -n "${STA_PASS}" ]]; then
        printf '#define WIFI_MGR_LOCAL_STA_PASSWORD     "%s"\n' "${STA_PASS}"
    fi
    if [[ -n "${AP_PASS}" ]]; then
        printf '#define WIFI_MGR_LOCAL_AP_PASSWORD      "%s"\n' "${AP_PASS}"
    fi
}

if [[ "${DRY_RUN}" -eq 1 ]]; then
    echo "# dry-run: would write ${OUT_FILE}"
    emit_file
    exit 0
fi

mkdir -p "${OUT_DIR}"
emit_file > "${OUT_FILE}"
echo "wrote ${OUT_FILE}"
